
echo -e " CLIENTNAME: $CLIENTNAME"
echo -e " SCRIPT VERSION: 1.2.5"
echo -e "╔════════════════════════════════════╗"
echo -e "        SSH & OVPN ACCOUNT ➠ 0"
echo -e " ———————————————————————————————————"
echo -e "          XRAY ACCOUNT ➠ 0"
echo -e " ———————————————————————————————————"
echo -e "          L2TP ACCOUNT ➠ 0"
echo -e " ———————————————————————————————————"
echo -e "         NOOBZ ACCOUNT ➠  0"
echo -e "╔════════════════════════════════════╗"
echo -e "║             MAIN MENU              ║"
echo -e "╚════════════════════════════════════╝"
echo -e "1. MENU SSH & OVPN"
echo -e "2. MENU XRAY"
echo -e "3. MENU L2TP"
echo -e "4. MENU NOOBZVPNS"
echo -e "5. SETTINGS"
echo -e "6. ON/OFF SERVICES"
echo -e "7. STATUS SERVICES"
echo -e "8. UPDATE SCRIPT"
echo -e "9. REBUILD OS"
echo -e "0. Exit"
echo -e "══════════════════════════════════════"
echo -e "EXP SCRIPT: 30 Hari Setelah Setup"
echo -e "REGIST BY : $CHAT_ID"
echo -e "══════════════════════════════════════"
echo -ne "Please select an option [0-9]: "
