#!/bin/bash

setup.sh by xydarknet - plain bash version

Function to get system info

get_sysinfo() { OS="$(lsb_release -d | cut -f2)" KERNEL="$(uname -r)" CPU_MODEL="$(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo | sed 's/^ *//')" CPU_SPEED="$(awk -F: '/cpu MHz/ {print $2; exit}' /proc/cpuinfo | sed 's/^ *//') MHz" CORES="$(nproc)" RAM="$(free -m | awk '/Mem:/ {print $2}') MB" USED_RAM="$(free -m | awk '/Mem:/ {print $3}') MB" DISK="$(df -h / | awk 'NR==2 {print $2}')" USED_DISK="$(df -h / | awk 'NR==2 {print $3}')" DOMAIN="xydark.biz.id" SDOMAIN="ns.xydark.biz.id" IP=$(curl -s ipv4.icanhazip.com) ISP=$(curl -s ipinfo.io/org | cut -d ' ' -f 2-) CITY=$(curl -s ipinfo.io/city) TIMEZONE=$(curl -s ipinfo.io/timezone) CLIENTNAME="kalya" VERSION="1.2.5" }

main_menu() { clear get_sysinfo echo "╔════════════════════════╗                                         ║ sc by t.me/xydark ║" echo "╔════════════════════════════════════╗" echo "║              SYS INFO              ║                             ╚════════════════════════════════════╝" echo " OS SYSTEM: $OS" echo " KERNEL TYPE: $KERNEL" echo " CPU MODEL: $CPU_MODEL" echo " CPU FREQUENCY: $CPU_SPEED ($CORES core)" echo " TOTAL RAM: $RAM Total / $USED_RAM Used" echo " TOTAL STORAGE: $DISK Total / $USED_DISK Used" echo " DOMAIN: $DOMAIN" echo " SLOWDNS DOMAIN: $SDOMAIN" echo " IP ADDRESS: $IP" echo " ISP: $ISP" echo " REGION: $CITY [$TIMEZONE]" echo " CLIENTNAME: $CLIENTNAME" echo " SCRIPT VERSION: $VERSION" echo "╔════════════════════════════════════╗" echo "        SSH & OVPN ACCOUNT ➠ 0" echo " ————————————————————————————————————" echo "          XRAY ACCOUNT ➠ 25" echo " ————————————————————————————————————" echo "          L2TP ACCOUNT ➠ 0" echo " ————————————————————————————————————" echo "         NOOBZ ACCOUNT ➠  0" echo "╔════════════════════════════════════╗" echo "║             MAIN MENU              ║" echo "╚════════════════════════════════════╝" echo "1. MENU SSH & OVPN" echo "2. MENU XRAY" echo "3. MENU L2TP" echo "4. MENU NOOBZVPNS" echo "5. SETTINGS" echo "6. ON/OFF SERVICES" echo "7. STATUS SERVICES" echo "8. UPDATE SCRIPT" echo "9. REBUILD OS" echo "0. Exit" echo "══════════════════════════════════════" echo "EXP SCRIPT: 2025-08-06 (27 days)" echo "REGIST BY : 1389219385 (id telegram)" echo "══════════════════════════════════════" read -p "Please select an option [0-9]: " menuopt case $menuopt in 1) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/menu-ssh | bash ;; 2) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/menu-xray | bash ;; 3) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/menu-l2tp | bash ;; 4) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/menu-noobz | bash ;; 5) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/menu-settings | bash ;; 6) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/menu-onoff | bash ;; 7) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/menu-status | bash ;; 8) wget -qO- https://raw.githubusercontent.com/xydarknet/x/main/update.sh | bash ;; 9) reboot ;; 0) exit 0 ;; *) echo "Invalid option"; sleep 1; main_menu ;; esac }

main_menu

