#!/bin/bash
# Auto update script from GitHub repo xydarknet/x

base_url="https://raw.githubusercontent.com/xydarknet/x/main"

files=(
  setup.sh
  system-info.sh
  request-ip.sh
  check-ip.sh
  menu/menu.sh
  menu/menu-xray.sh
  menu/menu-ssh.sh
  menu/menu-set.sh
  xray/addvless
  xray/addvmess
  xray/addtrojan
  xray/delvless
  xray/delvmess
  xray/deltrojan
  xray/renewvless
  xray/renewvmess
  xray/renewtrojan
  tools/update-script
)

for file in "${files[@]}"; do
  dest="/etc/xydark/$(basename "$file")"
  [[ "$file" == menu/* || "$file" == xray/* || "$file" == tools/* ]] && dest="/usr/bin/$(basename "$file")"
  wget -q -O "$dest" "$base_url/$file" && chmod +x "$dest"
done
